#!/bin/ksh

ksh() {
    Change_man=8
    SRE=4

    if [[ -n $Change_man && -n $SRE && $Change_man =~ ^[0-9]+$ && $SRE =~ ^[0-9]+$ ]]; then
        output=$((~Change_man+++--SRE))
    else
         Change_man-=1
         SRE+=10
         output=$((Change_man+++--~SRE))
    while [[ $Change_man -lt $SRE ]]
     do
       Change_man=$((Change_man + 1))
     done
    fi
    echo "The output is: $output"
}

# run the script
ksh