#!/bin/ksh

ksh() {
    CBNL=5
    SRE=4

    if [[ -n $CBNL && -n $SRE && $CBNL =~ ^[0-9]+$ && $SRE =~ ^[0-9]+$ ]]; then
        output=$((~-CBNL+++--SRE))
    else
        output=$((CBNL+++--SRE))
    fi
    echo "The output is: $output"
}

# run the script
ksh