---
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: "number"
      prompt: "Enter a number: "
      private: no

  tasks:
    - name: Calculate the result
      set_fact:
        result: "{{ (number | int * 3) if (number | int + 5) else (number | int - 5) }}"

    - name: Display the result
      debug:
        msg: "The result for the input number {{ number }} is {{ result }}"


#run the script by running ansible-playbook playbook.yml